### ISSUE TITLE
State of the module

### ISSUE THREAD

**Issue by aitorbouzas** [jorenvo/auth_u2f#1]
First of all, thank you very much for your contribution. This is not an issue, simply some questions I would like to ask about the actual state of your module.

Is there any known issue?
We are planning to use the Yubikeys with smartphones (the ones that have nfc). Have you tested your module with them?

Thank you.

**Comment by jorenvo** [comment]
Apologies for my late reply.

> Is there any known issue?

Do keep in mind this was a small weekend project I did to get more familiar with U2F. It has never been used in a production environment. That being said, the only known issue I'm aware of is that it doesn't work with Firefox. I think Firefox should have proper support for U2F now, so this can possibly be fixed. PRs welcome.

> We are planning to use the Yubikeys with smartphones (the ones that have nfc). Have you tested your module with them?

I have not. If it doesn't work it wouldn't be due to this module but due to the U2F API not working properly on the smartphones I think.

If you have tested it and found issues let me know by opening another issue and I'll take a look.

**Comment by aitorbouzas** [comment]
We tried it, it works perfectly with chrome and with NFC in smartphones. Unfortunately we are not going to implement it so we cannot help you anymore.
Thanks for the answer and for the module.

**Comment by jorenvo** [comment]
Cool, thanks for letting me know it works with NFC. I never tried and don't have an NFC key to test.
